web: 
  build: ./app
  volumes:
    - "./app:/src/app"
  ports: 
    - "80:3000"
  links:
    - rethink
    - postgres
redis: 
  image: redis:latest
  ports:
    - "6379:6379"
rethink:
  image: rethinkdb
postgres:
  image: postgres
